### ISSUE TITLE
Add support for GHC 7.10.3

### ISSUE THREAD

**Issue by dagit** [seL4/capDL-tool#1]
I needed to make several changes to get capDL-tool building with ghc 7.10.3.

First I had to relax the upper bound on base from 4.8 to 5. I also had to change the upper bound on filepath to 1.5. Most of the modules import `Data.Word` and on on GHC 7.10.3 this generates a warning. Perhaps the easiest way to fix this is by using the [base-compat](https://github.com/haskell-compat/base-compat#readme) package and then removing the `Data.Word` imports in favor of this combo:

```
import Prelude ()
import Prelude.Compat
```

Locally I just deleted the `Data.Word` imports, but presumably that will break things on ghc 7.8.x.

Finally in the Matrix module I needed to enable FlexibleContexts.

If these changes sound good I can send a pull request.

**Comment by corlewis** [comment]
These changes definitely sound good, although we'll want to ensure that ghc 7.8.x continues to be supported.

However, this repository has actually been deprecated and can now be found in https://github.com/seL4/capdl. I don't know if you're in a position to be able to switch to it, but that's where we'll want to make this fix.

**Comment by AdrianDanis** [comment]
Closing as this has been fixed at the [new repository](https://github.com/seL4/capdl)
